# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: Lints and Tests

# trigger:
#   branches:
#     include:
#       - "*" # must quote since "*" is a YAML reserved character; we want a string
trigger:
  - master

pool:
  name: pg

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - script: |
      yarn
    displayName: "yarn install"

  - script: |
      yarn lint-commit
    displayName: "yarn lint"

  - script: |
      yarn test -- --watchAll=false --silent
    displayName: "yarn test"

  - script: |
      yarn compile
    displayName: "yarn compile"
